# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-10-04 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=500)),
                ('page_title', models.CharField(max_length=200)),
                ('page_domain', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='logo',
            name='page_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dev_app.page'),
        ),
    ]
