# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-10-04 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dev_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pulled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pulled', models.DateTimeField(verbose_name='date pulled')),
                ('logo_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dev_app.logo')),
                ('page_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dev_app.page')),
            ],
        ),
    ]
