# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-10-04 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_app', '0002_pulled'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pulled',
            new_name='pull',
        ),
    ]
